let ObjectID = require("bson-objectid");
module.exports = {
  _id: ObjectID().str,
  docType: "defaultemailtemplate",
  responseNotificationTemplate:
    '<p><b>{{userName}} ({{userEmail}})</b> has responded to your {{type}} <b>{{title}}</b>.{{{marksPara}}}<p>Please click <a href="{{url}}">{{url}}</a> to view the response.</p><p>Regards,<p>{{regards}}</p></p>',
  quizMeTemplate:
    '<table  width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; width:100%; margin:0; padding:0"><tbody><tr><td  align="center" bgcolor="#F2F4F6" style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; padding:25px 0; text-align:center"><a href="{{appLink}}" target="_blank" rel="noopener noreferrer"  style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; color:#2F3133; font-size:16px; font-weight:bold; text-decoration:none">{{appTitle}}</a></td></tr><tr><td  width="100%" bgcolor="#F2F4F6" style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; width:100%; margin:0; padding:0; border-top:1px solid #EDEFF2; border-bottom:1px solid #EDEFF2; background-color:#F2F4F6"><table  align="center" cellpadding="0" cellspacing="0" style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; width:90%; margin:0 auto; padding:0"><tbody><tr><td  style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; padding:35px;background-color:white">{{{htmlString}}}</td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif"><table  align="center" width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; width:100%; margin:0 auto; padding:0; text-align:center"><tbody><tr><td bgcolor="#F2F4F6" style="font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; padding:35px"><p  style="margin-top:0; line-height:1.5em; font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif; color:#AEAEAE; font-size:12px; text-align:center">© 2017 <a href="{{appLink}}" target="_blank" rel="noopener noreferrer" style="color:#3869D4; font-family:Arial,\'Helvetica Neue\',Helvetica,sans-serif">{{appTitle}}</a>. All rights reserved. </p></td></tr></tbody></table></td></tr></tbody></table>'
};
